server:
  port: 8080

spring:
  datasource:
    username: root
    password: cthsq30896
    url: jdbc:mysql://localhost:3306/spring_app
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true