app:
  name: myApp
  maxConnection: 10
  enableFeature: true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox
    username: skillbox
    password: skillbox
    driver-class-name: org.postgresql.Driver


  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    generate-ddl: true






